---
order_manager:
  trend: down
  levels_intersection_threshold: '0.5'
  order_intersection_timeout: '150m'  # 2h 30m
emitter:
  price_open_to_level_ratio_threshold: '0.008'
  auto_close_in: '8h'
  stop_loss_level_percent: '1'
  profit_loss_ratio: '2'
  trend_window_size: 100
  interactions_window_size: 30
  levels_window_size_min: 50
  levels_window_size_max: 200
  min_levels_variation: '0.004'
  calc_trend_on: false
  min_level_interactions: 10
  sub_orders_count: 1
  create_lucky_order: false
  lucky_profit_loss_ratio: 2
  logging_settings:
    trend: false