---
order_manager:
  trend: down
  levels_intersection_threshold: '0.5'
  order_intersection_timeout: '150m'  # 2h 30m
emitter:
  price_open_to_level_ratio_threshold: '0.008'
  auto_close_in: '8h'
  stop_loss_level_percent: '1'
  profit_loss_ratio: '2'
  medium_window_size: 100
  small_window_size: 30
